Traceback (most recent call last):
  File "train_single_dqn.py", line 332, in <module>
    test(env, 100, "checkpoints/ckpt_3580000.pth")
  File "train_single_dqn.py", line 284, in test
    agent.q_network.load_state_dict(torch.load(load_path, map_location=torch.device('cpu')))
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LSTM_QNetwork:
	Unexpected key(s) in state_dict: "observation_encoder.conv.4.weight", "observation_encoder.conv.4.bias", "observation_encoder.conv.6.weight", "observation_encoder.conv.6.bias".
	size mismatch for observation_encoder.conv.0.weight: copying a param with shape torch.Size([8, 4, 2, 2]) from checkpoint, the shape in current model is torch.Size([8, 4, 3, 3]).
	size mismatch for observation_encoder.conv.2.weight: copying a param with shape torch.Size([16, 8, 2, 2]) from checkpoint, the shape in current model is torch.Size([8, 8, 2, 2]).
	size mismatch for observation_encoder.conv.2.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
	size mismatch for location_encoder.model.fc1.weight: copying a param with shape torch.Size([1936, 64]) from checkpoint, the shape in current model is torch.Size([144, 64]).
	size mismatch for location_encoder.model.fc1.bias: copying a param with shape torch.Size([1936]) from checkpoint, the shape in current model is torch.Size([144]).
	size mismatch for lstm.weight_ih_l0: copying a param with shape torch.Size([512, 5808]) from checkpoint, the shape in current model is torch.Size([512, 432]).
