2024-11-26 12:49:39,182 INFO    MainThread:59631 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_setup.py:_flush():79] Configure stats pid to 59631
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_setup.py:_flush():79] Loading settings from /Users/user/.config/wandb/settings
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_setup.py:_flush():79] Loading settings from /Users/user/Projects/foraging_game/wandb/settings
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'train_single_dqn.py', 'program_abspath': '/Users/user/Projects/foraging_game/train_single_dqn.py', 'program': 'train_single_dqn.py'}
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_init.py:_log_setup():533] Logging user logs to /Users/user/Projects/foraging_game/wandb/run-20241126_124939-g4eunhi4/logs/debug.log
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_init.py:_log_setup():534] Logging internal logs to /Users/user/Projects/foraging_game/wandb/run-20241126_124939-g4eunhi4/logs/debug-internal.log
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_init.py:init():619] calling init triggers
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'batch_size': 64, 'seq_length': 10, 'exploration_steps': 300000.0, 'buffer_size': 1000, 'max_eps': 0.8, 'min_eps': 0.2}
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_init.py:init():669] starting backend
2024-11-26 12:49:39,183 INFO    MainThread:59631 [wandb_init.py:init():673] sending inform_init request
2024-11-26 12:49:39,188 INFO    MainThread:59631 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-11-26 12:49:39,189 INFO    MainThread:59631 [wandb_init.py:init():686] backend started and connected
2024-11-26 12:49:39,198 INFO    MainThread:59631 [wandb_init.py:init():781] updated telemetry
2024-11-26 12:49:39,236 INFO    MainThread:59631 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-26 12:49:40,274 INFO    MainThread:59631 [wandb_init.py:init():867] starting run threads in backend
2024-11-26 12:49:40,466 WARNING MainThread:59631 [wandb_init.py:init():1260] interrupted
Traceback (most recent call last):
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 910, in init
    run._on_start()
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2496, in _on_start
    self._backend.interface.publish_python_packages(working_set())
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 301, in publish_python_packages
    for pkg in working_set:
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/site-packages/wandb/util.py", line 1928, in working_set
    yield InstalledDistribution(key=d.metadata["Name"], version=d.version)
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 428, in metadata
    self.read_text('METADATA')
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 762, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/Users/user/anaconda3/envs/robot/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
KeyboardInterrupt
2024-11-26 12:49:40,502 WARNING MsgRouterThr:59631 [router.py:message_loop():75] message_loop has been closed
